<a href="https://colab.research.google.com/github/ajaysaikiran2208/Deep-Learning-Models/blob/main/Building_an_Image_Classifier_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
from tensorflow import keras


In [4]:
fashion_mnist=keras.datasets.fashion_mnist
fashion_mnist

<module 'tensorflow.keras.datasets.fashion_mnist' from '/usr/local/lib/python3.7/dist-packages/tensorflow/keras/datasets/fashion_mnist/__init__.py'>

In [5]:
(X_train,y_train),(X_test,y_test)=fashion_mnist.load_data()

4423680/4422102 [==============================] - 0s 0us/step


In [6]:
X_train.shape,X_train.dtype

((60000, 28, 28), dtype('uint8'))

In [7]:
X_valid,X_train=X_train[0:5000]/255.0,X_train[5000:]/255.0

In [8]:
y_valid,y_train=y_train[:5000],y_train[5000:]

In [9]:
class_names=["T-shirt/top","Trouser","Pullover","Dress","Coat","Sandal","Shirt","Sneaker","Bag","Ankle boot"]

In [10]:
class_names[y_train[0]]

'Coat'

In [16]:
model=keras.models.Sequential()                                   #It creates a sequential model.This is the simplest kind of Keras model for neural networks that are just composed of a single stack of layers
model.add(keras.layers.Flatten(input_shape=[28,28]))              #to convert input image to 1-D array
model.add(keras.layers.Dense(300,activation="relu"))              #Dense layers manage its own weight,containing all the weights between the neurons and their input
model.add(keras.layers.Dense(100,activation="relu"))
model.add(keras.layers.Dense(20,activation="softmax"))

In [17]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_4 (Flatten)          (None, 784)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 300)               235500    
_________________________________________________________________
dense_2 (Dense)              (None, 100)               30100     
_________________________________________________________________
dense_3 (Dense)              (None, 20)                2020      
Total params: 267,620
Trainable params: 267,620
Non-trainable params: 0
_________________________________________________________________


In [18]:
model.layers

In [20]:
hidden1=model.layers[1]

In [21]:
weight,baises=hidden1.get_weights()

In [23]:
weight

array([[ 0.0074446 , -0.03481611, -0.0401899 , ...,  0.00284359,
         0.05407086,  0.02836483],
       [-0.035414  , -0.05268616, -0.00553449, ..., -0.03117387,
         0.01358683, -0.06530042],
       [-0.02775589, -0.00968538,  0.04344813, ...,  0.04588228,
        -0.05702924,  0.02265827],
       ...,
       [ 0.03083254,  0.06189741,  0.06378879, ...,  0.01621454,
         0.03384333,  0.01392084],
       [ 0.07033272,  0.04141501,  0.04232263, ...,  0.03364436,
         0.0652767 ,  0.00313783],
       [-0.00928836,  0.04279161,  0.01399355, ..., -0.03506767,
         0.05183157,  0.02124005]], dtype=float32)

In [25]:
model.compile(loss="sparse_categorical_crossentropy",optimizer="sgd",metrics=["accuracy"]) #we are using sparse_categorical_crossentropy because we will have prediction 1 for the class


In [27]:
history=model.fit(X_train,y_train,epochs=50,validation_data=(X_valid,y_valid))

Epoch 1/50
1719/1719 [==============================] - 7s 2ms/step - loss: 0.7400 - accuracy: 0.7575 - val_loss: 0.5108 - val_accuracy: 0.8346
Epoch 2/50
1719/1719 [==============================] - 4s 2ms/step - loss: 0.4981 - accuracy: 0.8266 - val_loss: 0.4482 - val_accuracy: 0.8444
Epoch 3/50
1719/1719 [==============================] - 4s 2ms/step - loss: 0.4515 - accuracy: 0.8432 - val_loss: 0.4485 - val_accuracy: 0.8504
Epoch 4/50
1719/1719 [==============================] - 4s 2ms/step - loss: 0.4224 - accuracy: 0.8518 - val_loss: 0.4384 - val_accuracy: 0.8466
Epoch 5/50
1719/1719 [==============================] - 4s 2ms/step - loss: 0.4021 - accuracy: 0.8594 - val_loss: 0.3959 - val_accuracy: 0.8650
Epoch 6/50
1719/1719 [==============================] - 4s 2ms/step - loss: 0.3866 - accuracy: 0.8634 - val_loss: 0.3857 - val_accuracy: 0.8652
Epoch 7/50
1719/1719 [==============================] - 4s 2ms/step - loss: 0.3700 - accuracy: 0.8687 - val_loss: 0.3585 - val_accuracy:

In [28]:
model.evaluate(X_test,y_test)

313/313 [==============================] - 1s 2ms/step - loss: 70.3067 - accuracy: 0.8511


[70.30674743652344, 0.8511000275611877]

In [29]:
X_new=X_test[:5]
y_proba=model.predict(X_new)
y_proba.round(2)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]], dtype=float32)

In [30]:
y_pred=model.predict_classes(X_new)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [31]:
y_pred

array([9, 2, 1, 1, 6])

In [33]:
import numpy as np


In [34]:
np.array(class_names)[y_pred]

array(['Ankle boot', 'Pullover', 'Trouser', 'Trouser', 'Shirt'],
      dtype='<U11')

In [35]:
y_new=y_test[:3]

In [36]:
y_new

array([9, 2, 1], dtype=uint8)